version: '3.7'
services:
  shopin_api:
    build: ./shopin_api
    container_name: shopinapi_kapsayici
    ports:
      - "8000:8000"
    networks:
      - benimagim

networks:
  benimagim:
    driver: bridge