version: '3.8'

networks:
  benimagim:
    name: shopin_benimagim

services:
  api:
    build: .  # SADECE NOKTA OLACAK (Ana klasörü temsil eder)
    container_name: shopinapi_kapsayici
    ports:
      - "8000:8000"
    networks:
      - benimagim
    depends_on:
      - mongo
      - redis
      - rabbitmq

  mongo:
    image: mongo:latest
    container_name: mongodb_kapsayici
    ports:
      - "27017:27017"
    networks:
      - benimagim

  redis:
    image: redis:latest
    container_name: shopin_redis
    ports:
      - "6379:6379"
    networks:
      - benimagim
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shopin_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - benimagim
    restart: always